language: java
services:
  - docker
env:
  global:
  - JAVA_OPTS="-Xmx1g"
jdk:
  - openjdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - docker save -o $HOME/docker_images/images.tar $(docker images -a -q)
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/docker_images
before_install:
  - docker load -i $HOME/docker_images/images.tar || true
  - docker-compose up -d elasticsearch
after_success:
  - if [ "$TRAVIS_JDK_VERSION" = "openjdk11" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi;
