version: '2.1'
services:
  webapp:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    image: ${IMAGE}:${VERSION}-dev
  elasticsearch:
    volumes:
      - esdata-dev:/usr/share/elasticsearch/data
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  esdata-dev:
    driver: local
